version: '3.8'

services:
  muscle-exercises-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./gifs:/app/gifs:ro  # Mount GIFs as read-only
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
